version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: project-idea-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "10002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: project-idea-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start-dev
    ports:
      - "10000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: project-idea-next-app
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "10001:3000"
  #   networks:
  #     - keycloak-network
  #   depends_on:
  #     - keycloak

volumes:
  postgres_data:
    name: project-idea-postgres-data

networks:
  keycloak-network:
    name: project-idea-network